extends Node
## Sound effects, loops and music. Sounds live in res://assets/audio/<name>.wav
## (generated by tools/gen_audio.py). "_loop" and "music_*" files loop (set in their .import).

const DIR := "res://assets/audio/%s.wav"
## Licensed tracks (see CREDITS.md) replace the synthesized music_<name> loops when present.
const MUSIC_DIR := "res://assets/music/%s.mp3"
const POOL_SIZE := 24

var _streams := {}
var _pool: Array[AudioStreamPlayer] = []
var _next := 0
var _music: Array[AudioStreamPlayer] = []
var _music_idx := 0
var _music_name := ""
var _ambience: AudioStreamPlayer
var _ambience_name := ""


func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	# Music and SFX buses come from res://default_bus_layout.tres.
	for i in POOL_SIZE:
		var p := AudioStreamPlayer.new()
		p.bus = "SFX"
		add_child(p)
		_pool.append(p)
	for i in 2:
		var m := AudioStreamPlayer.new()
		m.bus = "Music"
		add_child(m)
		_music.append(m)
	_ambience = AudioStreamPlayer.new()
	_ambience.bus = "SFX"
	add_child(_ambience)
	set_volumes(1.0, 1.0)


func stream(sound: String) -> AudioStream:
	if not _streams.has(sound):
		# Looping (loops + music) is set in each file's .import settings, not here:
		# the web build plays sounds as Web Audio samples and doesn't see runtime edits.
		var track := MUSIC_DIR % sound.trim_prefix("music_")
		if sound.begins_with("music_") and ResourceLoader.exists(track):
			_streams[sound] = load(track)
		else:
			_streams[sound] = load(DIR % sound)
	return _streams[sound]


## One-shot sound. pitch_jitter adds +-random variation.
func play(sound: String, volume_db := 0.0, pitch := 1.0, pitch_jitter := 0.0) -> void:
	var p := _pool[_next]
	_next = (_next + 1) % POOL_SIZE
	p.stream = stream(sound)
	p.volume_db = volume_db
	p.pitch_scale = maxf(0.05, pitch + randf_range(-pitch_jitter, pitch_jitter))
	p.play()


## Positional one-shot for things out in the world (wildlife, debris).
func play_at(sound: String, where: Vector2, volume_db := 0.0, pitch_jitter := 0.1) -> void:
	var p := AudioStreamPlayer2D.new()
	p.bus = "SFX"
	p.stream = stream(sound)
	p.volume_db = volume_db
	p.max_distance = 700.0
	p.attenuation = 1.5
	p.pitch_scale = 1.0 + randf_range(-pitch_jitter, pitch_jitter)
	p.global_position = where
	get_tree().current_scene.add_child(p)
	p.play()
	p.finished.connect(p.queue_free)


## A looping player owned by the caller (engine, rocket, wind...).
func make_loop(sound: String, parent: Node, volume_db := 0.0) -> AudioStreamPlayer:
	var p := AudioStreamPlayer.new()
	p.bus = "SFX"
	p.stream = stream(sound)
	p.volume_db = volume_db
	parent.add_child(p)
	return p


func music(track: String, fade := 1.0) -> void:
	if track == _music_name:
		return
	_music_name = track
	var old := _music[_music_idx]
	_music_idx = 1 - _music_idx
	var cur := _music[_music_idx]
	var tw := create_tween().set_parallel()
	if old.playing:
		tw.tween_property(old, "volume_db", -60.0, fade)
		tw.chain().tween_callback(old.stop)
	if track != "":
		cur.stream = stream(track)
		cur.volume_db = -40.0
		cur.play()
		tw.tween_property(cur, "volume_db", -6.0, fade)


func ambience(track: String, volume_db := -14.0) -> void:
	if track == _ambience_name:
		return
	_ambience_name = track
	_ambience.stop()
	if track != "":
		_ambience.stream = stream(track)
		_ambience.volume_db = volume_db
		_ambience.play()


func set_volumes(music_vol: float, sfx_vol: float) -> void:
	AudioServer.set_bus_volume_db(AudioServer.get_bus_index("Music"), linear_to_db(maxf(music_vol, 0.0001)))
	AudioServer.set_bus_volume_db(AudioServer.get_bus_index("SFX"), linear_to_db(maxf(sfx_vol, 0.0001)))
